apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-cert-manager
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://10.0.1.137:6443'
  source:
    path: demo/cert-manager
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-portworx-operator
spec:
  destination:
    name: ''
    namespace: portworx
    server: 'https://10.0.1.137:6443'
  source:
    path: demo/px-operator
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-portworx
spec:
  destination:
    name: ''
    namespace: portworx
    server: 'https://10.0.1.137:6443'
  source:
    path: demo/px
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-px-central
spec:
  sources:
  - repoURL: 'http://charts.portworx.io/'
    chart: px-central
    targetRevision: 2.4.0
    helm:
      valueFiles:
      - $values/demo/px-central/values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'px-central'
    server: 'https://10.0.1.137:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-metallb
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: 'https://10.0.1.137:6443'
  source:
    path: demo/metallb
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false