apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nc-postgres
spec:
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: 12.2.6
    helm:
      valueFiles:
      - $values/prod/nc/postgres-values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'nc'
    server: 'https://10.0.1.122:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  sources:
  - repoURL: 'https://nextcloud.github.io/helm/'
    chart: nextcloud
    targetRevision: 3.5.4
    helm:
      valueFiles:
      - $values/prod/nc/nextcloud-values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'nc'
    server: 'https://10.0.1.122:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nc-ingress
spec:
  destination:
    name: ''
    namespace: nc
    server: 'https://10.0.1.122:6443'
  source:
    path: prod/nc/ingress
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
