apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: art101
spec:
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: wordpress
    targetRevision: 15.2.57
    helm:
      valueFiles:
      - $values/prod/wordpress/values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'art101'
    server: 'https://10.0.1.136:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amoc
spec:
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: wordpress
    targetRevision: 15.2.57
    helm:
      valueFiles:
      - $values/prod/wordpress/values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'amoc'
    server: 'https://10.0.1.136:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hhk
spec:
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: wordpress
    targetRevision: 15.2.57
    helm:
      valueFiles:
      - $values/prod/wordpress/values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'hhk'
    server: 'https://10.0.1.136:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
