apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nc-postgres
spec:
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgressql
    targetRevision: 12.2.6
    helm:
      valueFiles:
      - $values/prod/nc/postgres-values.yaml
  - repoURL: 'https://github.com/ccrow42/argocd'
    ref: values
  destination:
    name: ''
    namespace: 'nc'
    server: 'https://10.0.1.122:6443'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
