kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-proxy-volume-nextcloud
provisioner: kubernetes.io/portworx-volume
parameters:
  proxy_endpoint: "nfs://10.0.1.8"
  proxy_nfs_exportpath: "/volume1/nextcloud"
  mount_options: "vers=3.0"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: nc
  name: nc-data
  labels:
    app: nginx
spec:
  storageClassName: portworx-proxy-volume-nextcloud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
