apiVersion: v1
kind: Service
metadata:
  namespace: externalsvc
  name: synology-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
    - protocol: TCP
      name: https
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: externalsvc
  name: synology-svc
subsets:
  - addresses:
    - ip: 10.0.1.8
    ports:
    - port: 5000
      name: http
    - port: 5001
      name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress-synology
  namespace: externalsvc
spec:
  tls:
  - hosts:
    - synology.ccrow.org
      secretName: synology-tls
  rules:
  - host: synology.ccrow.org
    http:
      paths:
      - backend:
          service:
            name: synology-svc
            port:
              number: 5000
        path: /
        pathType: ImplementationSpecific
  - host: synology.ccrow.org
    http:
      paths:
      - backend:
          service:
            name: synology-svc
            port:
              number: 5001
        path: /
        pathType: ImplementationSpecific
