apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valheim
spec:
  destination:
    name: ''
    namespace: valheim
    server: 'https://10.0.1.131:6443'
  source:
    path: test/valheim
    repoURL: 'https://github.com/ccrow42/argocd'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
